# Generated by Django 3.2.25 on 2025-04-01 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_role_permissions'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['department__name', 'name'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Optional department this project belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_projects', to='organization.department'),
        ),
    ]
