# Generated by Django 3.2.25 on 2025-05-29 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_auto_20250521_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('BLOCKED', 'Blocked'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REASSIGNED', 'Reassigned'), ('IN_REVIEW', 'In Review'), ('ON_HOLD', 'On Hold')], default='TODO', help_text='Current status of the task', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the change')),
                ('field_name', models.CharField(help_text='The name of the field that was changed', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='The old value of the field', null=True)),
                ('new_value', models.TextField(blank=True, help_text='The new value of the field', null=True)),
                ('comment', models.TextField(blank=True, help_text='Optional comment describing the change', null=True)),
                ('task', models.ForeignKey(help_text='The task this history entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.task')),
                ('user', models.ForeignKey(blank=True, help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task History',
                'verbose_name_plural': 'Task Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
