# Generated by Django 3.2.25 on 2025-05-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20250529_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskhistory',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='new_value',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='old_value',
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='task_state',
            field=models.JSONField(default=dict, help_text='The complete state of the task at this point in time'),
        ),
    ]
