# Generated by Django 3.2.25 on 2025-05-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20250529_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='task_state',
            field=models.JSONField(help_text='The complete state of the task at this point in time'),
        ),
    ]
