# Generated by Django 3.2.25 on 2025-07-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_taskhistory_task_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='change_description',
            field=models.CharField(default='', help_text='A human-readable description of the change.', max_length=255),
        ),
    ]
