# Generated by Django 3.2.25 on 2025-07-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_taskhistory_change_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('BLOCKED', 'Blocked'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IN_REVIEW', 'In Review'), ('ON_HOLD', 'On Hold')], default='TODO', help_text='Current status of the task', max_length=20),
        ),
    ]
