# Generated by Django 3.2.25 on 2025-07-02 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tasks', '0009_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='The content type of the object this task is related to (e.g., Meeting, Memo).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='task',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='The ID of the related object.', null=True),
        ),
    ]
