# Generated by Django 3.2.21 on 2023-10-11 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('statistics', '0001_initial'), ('statistics', '0002_unitrank_is_court'), ('statistics', '0003_financialyear'), ('statistics', '0004_financialquarter'), ('statistics', '0005_unit'), ('statistics', '0006_unit_is_court'), ('statistics', '0007_months'), ('statistics', '0008_auto_20231009_1427'), ('statistics', '0009_dcrtdata_division'), ('statistics', '0010_alter_division_code'), ('statistics', '0011_auto_20231009_1510'), ('statistics', '0012_alter_dcrtdata_division'), ('statistics', '0013_alter_dcrtdata_division'), ('statistics', '0014_auto_20231009_1932'), ('statistics', '0015_auto_20231009_2005'), ('statistics', '0016_alter_dcrtdata_division'), ('statistics', '0017_dcrtdata_name_of_court'), ('statistics', '0018_auto_20231009_2106'), ('statistics', '0019_alter_dcrtdata_case_coming_for'), ('statistics', '0020_auto_20231009_2115'), ('statistics', '0021_alter_months_financial_quarter'), ('statistics', '0022_dcrtdata_unit_rank')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_court', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialQuarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.financialyear')),
            ],
        ),
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('month_number', models.IntegerField(help_text='Number of days in the month')),
                ('financial_quarter', models.IntegerField(help_text='The financial quarter in which the month falls. It is either 1, 2, 3, or 4')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unique_id', models.CharField(max_length=255)),
                ('unique_code', models.CharField(max_length=255)),
                ('head_id_fk', models.IntegerField()),
                ('subhead_id_fk', models.IntegerField()),
                ('has_division', models.BooleanField(default=False)),
                ('unit_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.unitrank')),
                ('is_court', models.BooleanField(default=False)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.division')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.unit')),
            ],
        ),
        migrations.CreateModel(
            name='DcrtData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.financialquarter')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.financialyear')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.months')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.unit')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.division')),
                ('adjournment_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('appeal_number_code', models.CharField(blank=True, max_length=255, null=True)),
                ('appeal_number_court_name', models.CharField(blank=True, max_length=255, null=True)),
                ('appeal_number_number', models.IntegerField(blank=True, null=True)),
                ('appeal_number_year', models.IntegerField(blank=True, null=True)),
                ('case_coming_for', models.CharField(blank=True, max_length=255, null=True)),
                ('case_number_code', models.CharField(blank=True, max_length=255, null=True)),
                ('case_number_day', models.IntegerField(blank=True, null=True)),
                ('case_number_month', models.CharField(blank=True, max_length=255, null=True)),
                ('case_number_number', models.IntegerField(blank=True, null=True)),
                ('case_number_year', models.IntegerField(blank=True, null=True)),
                ('case_outcome', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_next_activity_day', models.IntegerField(blank=True, null=True)),
                ('date_of_next_activity_month', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_next_activity_year', models.IntegerField(blank=True, null=True)),
                ('judicial_officer_1', models.CharField(blank=True, max_length=255, null=True)),
                ('judicial_officer_2', models.CharField(blank=True, max_length=255, null=True)),
                ('judicial_officer_3', models.CharField(blank=True, max_length=255, null=True)),
                ('judicial_officer_4', models.CharField(blank=True, max_length=255, null=True)),
                ('judicial_officer_5', models.CharField(blank=True, max_length=255, null=True)),
                ('judicial_officer_6', models.CharField(blank=True, max_length=255, null=True)),
                ('last_date_of_submission_of_case_file_day', models.CharField(blank=True, max_length=255, null=True)),
                ('last_date_of_submission_of_case_file_month', models.CharField(blank=True, max_length=255, null=True)),
                ('last_date_of_submission_of_case_file_year', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_accused_remanded', models.IntegerField(blank=True, null=True)),
                ('no_of_defendants_accused_female', models.IntegerField(blank=True, null=True)),
                ('no_of_defendants_accused_male', models.IntegerField(blank=True, null=True)),
                ('no_of_defendants_accused_organization', models.IntegerField(blank=True, null=True)),
                ('no_of_plaintiffs_or_appellants_female', models.IntegerField(blank=True, null=True)),
                ('no_of_plaintiffs_or_appellants_male', models.IntegerField(blank=True, null=True)),
                ('no_of_plaintiffs_or_appellants_organization', models.IntegerField(blank=True, null=True)),
                ('no_of_witnesses_in_court_d', models.IntegerField(blank=True, null=True)),
                ('no_of_witnesses_in_court_w', models.IntegerField(blank=True, null=True)),
                ('parties_have_legal_representation', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('specific_case_type', models.CharField(blank=True, max_length=255, null=True)),
                ('today_date_day', models.IntegerField(blank=True, null=True)),
                ('today_date_month', models.CharField(blank=True, max_length=255, null=True)),
                ('today_date_year', models.CharField(blank=True, max_length=255, null=True)),
                ('judicial_officer_7', models.CharField(blank=True, max_length=255, null=True)),
                ('judicial_officer_8', models.CharField(blank=True, max_length=255, null=True)),
                ('name_of_court', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_rank', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='statistics.unitrank')),
            ],
        ),
    ]
