# Generated by Django 4.2.13 on 2025-02-06 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("code", models.CharField(max_length=50)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FinancialYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Months",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "month_number",
                    models.IntegerField(help_text="Number of days in the month"),
                ),
                (
                    "financial_quarter",
                    models.IntegerField(
                        help_text="The financial quarter in which the month falls. It is either 1, 2, 3, or 4"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("unique_id", models.CharField(max_length=255)),
                ("unique_code", models.CharField(max_length=255)),
                ("head_id_fk", models.IntegerField()),
                ("subhead_id_fk", models.IntegerField()),
                ("has_division", models.BooleanField(default=False)),
                ("is_court", models.BooleanField(default=False)),
                ("latitude", models.FloatField(default=0)),
                ("longitude", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UnitRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_court", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UnitDivision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="statistics.division",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="statistics.unit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="unit",
            name="unit_rank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="statistics.unitrank"
            ),
        ),
        migrations.CreateModel(
            name="FinancialQuarter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "quarter_number",
                    models.IntegerField(
                        help_text="The financial quarter in which the month falls. It is either 1, 2, 3, or 4"
                    ),
                ),
                (
                    "financial_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="statistics.financialyear",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DcrtData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("today_date_day", models.IntegerField(blank=True, null=True)),
                (
                    "today_date_month",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "today_date_year",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "name_of_court",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "case_number_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("case_number_number", models.IntegerField(blank=True, null=True)),
                ("case_number_day", models.IntegerField(blank=True, null=True)),
                (
                    "case_number_month",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("case_number_year", models.IntegerField(blank=True, null=True)),
                (
                    "appeal_number_court_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "appeal_number_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("appeal_number_number", models.IntegerField(blank=True, null=True)),
                ("appeal_number_year", models.IntegerField(blank=True, null=True)),
                (
                    "specific_case_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "judicial_officer_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "judicial_officer_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "judicial_officer_3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "judicial_officer_4",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "judicial_officer_5",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "judicial_officer_6",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "judicial_officer_7",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "judicial_officer_8",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "case_coming_for",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "case_outcome",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "adjournment_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "date_of_next_activity_day",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "date_of_next_activity_month",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "date_of_next_activity_year",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "no_of_plaintiffs_or_appellants_male",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "no_of_plaintiffs_or_appellants_female",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "no_of_plaintiffs_or_appellants_organization",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "no_of_defendants_accused_male",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "no_of_defendants_accused_female",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "no_of_defendants_accused_organization",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "parties_have_legal_representation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "no_of_witnesses_in_court_d",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "no_of_witnesses_in_court_w",
                    models.IntegerField(blank=True, null=True),
                ),
                ("no_of_accused_remanded", models.IntegerField(blank=True, null=True)),
                (
                    "last_date_of_submission_of_case_file_day",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_date_of_submission_of_case_file_month",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_date_of_submission_of_case_file_year",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="statistics.division",
                    ),
                ),
                (
                    "financial_quarter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="statistics.financialquarter",
                    ),
                ),
                (
                    "financial_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="statistics.financialyear",
                    ),
                ),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="statistics.months",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="statistics.unit",
                    ),
                ),
            ],
        ),
    ]
