# Generated by Django 3.2.21 on 2023-10-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitrank',
            name='is_court',
            field=models.BooleanField(default=False),
        ),
    ]
