# Generated by Django 3.2.21 on 2023-10-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0001_initial_squashed_0022_dcrtdata_unit_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcrtdata',
            name='unit_rank',
        ),
    ]
