# Generated by Django 3.2.21 on 2023-10-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0002_remove_dcrtdata_unit_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialquarter',
            name='quarter_number',
            field=models.IntegerField(default=1, help_text='The financial quarter in which the month falls. It is either 1, 2, 3, or 4'),
            preserve_default=False,
        ),
    ]
