# Generated by Django 3.2.25 on 2025-04-07 15:10

from django.db import migrations, models
import django.db.models.deletion

# ELRC Case Categories to seed
ELRC_CATEGORIES = [
    {"name": "Appeals", "code": "ELRCA"},
    {"name": "Claim/Causes", "code": "ELRCC"},
    {"name": "Collective Bargaining Agreements (CBAs)", "code": "ELRCBA"},
    {"name": "Judicial Review", "code": "ELRCJR"},
    {"name": "Miscellaneous Applications", "code": "ELRCMISC"},
    {"name": "Petitions", "code": "ELRCPET"},
]

def seed_case_categories(apps, schema_editor):
    """Seed initial case categories for ELRC"""
    CaseCategory = apps.get_model('statistics', 'CaseCategory')
    UnitRank = apps.get_model('statistics', 'UnitRank')
    db_alias = schema_editor.connection.alias

    # Get or create ELRC rank
    try:
        elrc_rank = UnitRank.objects.using(db_alias).get(name__icontains='ELRC')
    except UnitRank.DoesNotExist:
        print("Warning: ELRC rank not found. Creating with default name.")
        elrc_rank = UnitRank.objects.using(db_alias).create(
            name="EMPLOYMENT AND LABOUR RELATIONS COURT",
            is_court=True
        )

    # Create categories
    created_count = 0
    for cat_data in ELRC_CATEGORIES:
        cat, created = CaseCategory.objects.using(db_alias).get_or_create(
            code=cat_data['code'],
            unit_rank=elrc_rank,
            defaults={
                'name': cat_data['name'],
                'description': f"ELRC {cat_data['name']} cases"
            }
        )
        if created:
            created_count += 1
            print(f"Created case category: {cat.code} - {cat.name}")

    print(f"\nCase categories seeding complete. Created {created_count} new categories.")


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0003_auto_20250407_1454'),
    ]

    operations = [
        # Step 1: Remove temporary field from previous migration
        migrations.RemoveField(
            model_name='dcrtdata',
            name='case_activity_type',
        ),

        # Step 2: Create the CaseCategory model
        migrations.CreateModel(
            name='CaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_categories', to='statistics.unitrank')),
            ],
            options={
                'verbose_name_plural': 'Case Categories',
                'ordering': ['unit_rank', 'code'],
                'unique_together': {('code', 'unit_rank'), ('name', 'unit_rank')},
            },
        ),
        
        # Step 3: Seed initial ELRC categories
        migrations.RunPython(
            seed_case_categories,
            reverse_code=migrations.RunPython.noop
        ),
    ]
