# Generated by Django 3.2.21 on 2023-10-07 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0003_financialyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialQuarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.financialyear')),
            ],
        ),
    ]
