# Generated by Django 3.2.25 on 2025-04-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0007_create_adjournment_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjournmentreason',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
