# Generated by Django 3.2.25 on 2025-06-10 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0008_alter_adjournmentreason_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='template_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_for', to='statistics.unit'),
        ),
    ]
