# Generated by Django 3.2.25 on 2025-06-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0009_auto_20250610_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='dcrt_unique_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
