# Generated by Django 3.2.25 on 2025-06-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0012_update_unit_ranks'),
        ('statistics', '0013_update_unit_ranks'),
    ]

    operations = [
    ]
