# Generated by Django 3.2.25 on 2025-02-08 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('is_replication', models.BooleanField(default=False)),
                ('source_court', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(max_length=100)),
                ('situation_before', models.TextField()),
                ('description', models.TextField()),
                ('solution', models.TextField()),
                ('replication_potential', models.TextField()),
                ('individuals_involved', models.TextField()),
                ('stakeholders_affected', models.TextField()),
                ('status', models.CharField(choices=[('innovation', 'Innovation'), ('best_practice', 'Best Practice'), ('rejected', 'Rejected')], default='innovation', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_innovations', to=settings.AUTH_USER_MODEL)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovations', to='statistics.unit')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.financialyear')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_innovations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_all_innovations', 'Can view all innovations'), ('approve_innovation', 'Can approve innovation'), ('reject_innovation', 'Can reject innovation'), ('can_view_innovation', 'Can view innovation'), ('can_change_innovation', 'Can change innovation'), ('can_delete_innovation', 'Can delete innovation')],
            },
        ),
        migrations.CreateModel(
            name='InnovationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='innovation_attachments/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='innovations.innovation')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
