# Generated by Django 3.2.18 on 2023-02-19 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20230219_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastpaper',
            name='course',
        ),
        migrations.DeleteModel(
            name='CoursePastPaper',
        ),
        migrations.DeleteModel(
            name='PastPaper',
        ),
    ]
