# Generated by Django 3.2.25 on 2025-07-02 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memos', '0002_auto_20250702_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='due_date',
            field=models.DateField(blank=True, help_text='Date by which action or response is required.', null=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='memo',
            name='recipient_external_name',
            field=models.CharField(blank=True, help_text='Name of external recipient, if applicable.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='recipient_external_organization',
            field=models.CharField(blank=True, help_text='Organization of external recipient, if applicable.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='sender_external_name',
            field=models.CharField(blank=True, help_text='Name of external sender, if applicable.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='sender_external_organization',
            field=models.CharField(blank=True, help_text='Organization of external sender, if applicable.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='sender_user',
            field=models.ForeignKey(blank=True, help_text='Internal user who sent the memo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_memos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memo',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('archived', 'Archived'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('needs_clarification', 'Needs Clarification'), ('completed', 'Completed')], default='draft', max_length=50),
        ),
    ]
