# Generated by Django 3.2.18 on 2023-02-19 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastpapers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PastPaper',
        ),
    ]
