# Generated by Django 4.2.13 on 2025-02-13 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0002_role_permissions"),
        ("statistics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("unit_of_measure", models.CharField(blank=True, max_length=50)),
                ("weight", models.IntegerField(default=0)),
                ("baseline_2023_2024", models.CharField(blank=True, max_length=100)),
                ("target_2024_2025", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_indicators",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicators",
                        to="organization.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Indicator",
                "verbose_name_plural": "Performance Indicators",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PMMU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "financial_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pmmus",
                        to="statistics.financialyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "PMMU Understanding",
                "verbose_name_plural": "PMMU Understandings",
                "ordering": ["-financial_year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IndicatorNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="pmmu.indicator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicator Note",
                "verbose_name_plural": "Indicator Notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="indicator",
            name="pmmu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indicators",
                to="pmmu.pmmu",
            ),
        ),
    ]
