# Generated by Django 4.2.13 on 2025-02-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pmmu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
