# Generated by Django 4.2.13 on 2025-02-14 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("statistics", "0001_initial"),
        ("pmmu", "0002_indicator_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicatorCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name of the indicator category (e.g., core_mandate - used internally)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="User-friendly display name (e.g., A. CORE MANDATE - shown to users, optional)",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicator Category",
                "verbose_name_plural": "Indicator Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="indicatornote",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created the note",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="indicatornote",
            name="note_text",
            field=models.TextField(help_text="Text content of the note"),
        ),
        migrations.AlterField(
            model_name="pmmu",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description of the PMMU document"
            ),
        ),
        migrations.AlterField(
            model_name="pmmu",
            name="financial_year",
            field=models.ForeignKey(
                help_text="Financial Year this PMMU applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pmmus",
                to="statistics.financialyear",
            ),
        ),
        migrations.AlterField(
            model_name="pmmu",
            name="name",
            field=models.CharField(
                help_text="Name of the PMMU document (e.g., PMMU Understanding 2024-2025)",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="PerformanceIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="Description of the performance indicator (e.g., Institutionalize Performance Management)"
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        help_text="Unit of measurement (e.g., %, No.)", max_length=50
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        default=0,
                        help_text="Weight or importance of this indicator in percentage (e.g., 10)",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        help_text="Category this indicator belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="indicators",
                        to="pmmu.indicatorcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Indicator",
                "verbose_name_plural": "Performance Indicators",
                "ordering": ["subcategory__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="FinancialYearPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        help_text="Target performance for this financial year",
                        max_length=100,
                    ),
                ),
                (
                    "baseline",
                    models.CharField(
                        blank=True,
                        help_text="Baseline performance for this financial year (could be from previous FY)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "actual",
                    models.CharField(
                        blank=True,
                        help_text="Actual performance achieved in this financial year",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "financial_year",
                    models.ForeignKey(
                        help_text="Financial Year for this performance data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_data",
                        to="statistics.financialyear",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        help_text="Performance Indicator",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_year_data",
                        to="pmmu.performanceindicator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Year Performance Data",
                "verbose_name_plural": "Financial Year Performance Data",
                "ordering": [
                    "financial_year",
                    "indicator__subcategory__name",
                    "indicator__name",
                ],
                "unique_together": {("financial_year", "indicator")},
            },
        ),
        migrations.AlterField(
            model_name="indicatornote",
            name="indicator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="pmmu.performanceindicator",
            ),
        ),
        migrations.DeleteModel(
            name="Indicator",
        ),
    ]
