# Generated by Django 4.2.13 on 2025-02-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pmmu", "0003_indicatorcategory_alter_indicatornote_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="performanceindicator",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description of the indicator"
            ),
        ),
    ]
