# Generated by Django 3.2.25 on 2025-02-05 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
        ('document_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meeting_type', models.CharField(choices=[('department', 'Department Internal'), ('director', 'With Director'), ('committee', 'Committee Meeting'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('meeting_mode', models.CharField(choices=[('physical', 'Physical'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], default='physical', max_length=20)),
                ('physical_location', models.CharField(blank=True, max_length=255, null=True)),
                ('virtual_meeting_url', models.URLField(blank=True, null=True)),
                ('virtual_meeting_id', models.CharField(blank=True, help_text='Meeting ID for virtual platform', max_length=100, null=True)),
                ('virtual_meeting_password', models.CharField(blank=True, help_text='Password for virtual meeting', max_length=50, null=True)),
                ('virtual_platform', models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('meet', 'Google Meet'), ('other', 'Other Platform')], max_length=50, null=True)),
                ('agenda', models.TextField()),
                ('minutes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('has_recording', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='organization.department')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
                'permissions': [('view_all_meetings', 'Can view all meetings across departments'), ('manage_department_meetings', 'Can manage department meetings')],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('organizer', 'Organizer'), ('attendee', 'Attendee'), ('guest', 'Guest')], default='attendee', max_length=20)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting Participant',
                'verbose_name_plural': 'Meeting Participants',
                'unique_together': {('meeting', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='MeetingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Meeting Action Item',
                'verbose_name_plural': 'Meeting Action Items',
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(through='meetings.MeetingParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MeetingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('agenda', 'Agenda'), ('minutes', 'Minutes'), ('presentation', 'Presentation'), ('report', 'Report'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the document')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_management.document')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Meeting Document',
                'verbose_name_plural': 'Meeting Documents',
                'ordering': ['-uploaded_at'],
                'unique_together': {('meeting', 'document')},
            },
        ),
    ]
