# Generated by Django 3.2.25 on 2025-06-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_populate_meeting_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingparticipant',
            name='role',
            field=models.CharField(choices=[('attendee', 'Attendee'), ('guest', 'Guest')], default='attendee', max_length=20),
        ),
    ]
