# Generated by Django 3.2.25 on 2025-06-09 12:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0003_department_email'),
        ('meetings', '0005_auto_20250603_1421'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together={('date', 'title', 'department', 'organizer')},
        ),
    ]
