# Generated by Django 3.2.25 on 2025-07-02 10:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0007_merge_20250610_0953'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together={('date', 'title', 'organizer')},
        ),
    ]
