# Generated by Django 3.2.25 on 2025-07-02 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('meetings', '0008_alter_meeting_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='The content type of the object this meeting is related to (e.g., Task, Memo).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='The ID of the related object.', null=True),
        ),
    ]
