# Generated by Django 3.2.25 on 2025-02-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Budget Categories',
            },
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkplanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('budget_code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('regular', 'Regular Activity'), ('transformative', 'Transformative Initiative')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budgetcategory')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.financialyear')),
            ],
        ),
        migrations.CreateModel(
            name='TransformativeInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implementation_status', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('progress', models.IntegerField(default=0)),
                ('workplan_item', models.OneToOneField(limit_choices_to={'item_type': 'transformative'}, on_delete=django.db.models.deletion.CASCADE, to='budget.workplanitem')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('baseline', models.CharField(blank=True, max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('measurement_frequency', models.CharField(max_length=50)),
                ('workplan_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.workplanitem')),
            ],
        ),
        migrations.CreateModel(
            name='QuarterlyAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('workplan_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.workplanitem')),
            ],
            options={
                'unique_together': {('workplan_item', 'quarter')},
            },
        ),
    ]
