# Generated by Django 4.2.13 on 2025-02-07 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        ("document_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhysicalMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_number", models.CharField(max_length=100, unique=True)),
                (
                    "mail_type",
                    models.CharField(
                        choices=[("incoming", "Incoming"), ("outgoing", "Outgoing")],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(help_text="Brief description of mail contents"),
                ),
                ("date_received", models.DateTimeField(blank=True, null=True)),
                ("date_sent", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("express", "Express"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("confidential", models.BooleanField(default=False)),
                (
                    "file_number",
                    models.CharField(
                        help_text="Physical file reference number", max_length=100
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("hand_delivery", "Hand Delivery"),
                            ("postal", "Postal Service"),
                            ("courier", "Courier Service"),
                            ("diplomatic_bag", "Diplomatic Bag"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in grams",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "postage_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("courier_name", models.CharField(blank=True, max_length=100)),
                (
                    "courier_tracking_number",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received at Registry"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("pending_dispatch", "Pending Dispatch"),
                            ("dispatched", "Dispatched"),
                            ("acknowledged", "Acknowledgment Received"),
                            ("archived", "Archived"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sender_name", models.CharField(max_length=255)),
                ("sender_address", models.TextField()),
                ("sender_phone", models.CharField(blank=True, max_length=50)),
                ("recipient_name", models.CharField(max_length=255)),
                ("recipient_address", models.TextField()),
                ("recipient_phone", models.CharField(blank=True, max_length=50)),
                ("requires_response", models.BooleanField(default=False)),
                ("response_deadline", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_physical_mails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="physical_mails",
                        to="organization.department",
                    ),
                ),
                (
                    "response_mail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="original_mail",
                        to="mail.physicalmail",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_mark_confidential", "Can mark mail as confidential"),
                    ("view_confidential_mail", "Can view confidential mail"),
                    ("process_incoming_mail", "Can process incoming mail"),
                    ("dispatch_outgoing_mail", "Can dispatch outgoing mail"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MailMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_location", models.CharField(max_length=255)),
                ("to_location", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                ("received_by", models.CharField(blank=True, max_length=255)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "handler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="mail.physicalmail",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MailAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "attachment_type",
                    models.CharField(
                        help_text="Type of physical attachment", max_length=100
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "condition",
                    models.CharField(
                        help_text="Condition of the attachment", max_length=100
                    ),
                ),
                (
                    "digital_copy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="physical_attachments",
                        to="document_management.document",
                    ),
                ),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="mail.physicalmail",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MailAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "current_location",
                    models.CharField(
                        help_text="Current physical location of the mail",
                        max_length=255,
                    ),
                ),
                ("acknowledgment_required", models.BooleanField(default=True)),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_by", models.CharField(blank=True, max_length=255)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mail_assignments_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_mails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="mail.physicalmail",
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="MailActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("receive", "Received at Registry"),
                            ("register", "Registered"),
                            ("assign", "Assigned"),
                            ("forward", "Forwarded"),
                            ("process", "Processed"),
                            ("dispatch", "Dispatched"),
                            ("deliver", "Delivered"),
                            ("archive", "Archived"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.CharField(
                        help_text="Physical location where activity occurred",
                        max_length=255,
                    ),
                ),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="mail.physicalmail",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mail Activities",
                "ordering": ["-timestamp"],
            },
        ),
    ]
